BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXX
  XXXXXXXXXXX
  BB BBBBBBBBBBB
    XXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX XXX XXXXXXXXXXXXXXX
  BBBBB
  XXXXX XXXXXXXXXXXXX XXXXXXXXXX
    BBBBBBBBBB 
    XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXXXXX
    XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX
  XXXXXXX XXXXX XXXXXXXXXXXX
  XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBXXXXXXXXXXXXXX
  XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBXXXXXXXXXXXXX
  XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBXXXXXXXXXXXX
  XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBBXXXXXXXXXXXXXXX
XXX gettext(u'Забыли пароль') X XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBXX gettext(u'Reset it') XXXXXXXXX
XXXXXX XXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Register') XXXXXXXXX
XXXXXX
BBBBBBBB
