BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXX XXXXXXXXXXX
    BBBBBBBBBB 
    XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXX XXXXXXX XX XXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX
XXXXXX
BBBBBBBB
