BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXX
  BBB B BB BBBB
    
  BBBBBB
  XXXXX XXXXXXXXXXXXX XXXXXXXXXXX
    BBBBBBBBBB 
    XXXXXXX
    XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX
    XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XX XXXXXX XXXXXXXXX X XXXXX XXXXXX XXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXX XXXX XXXXXXX XXXXXXX XX XXXXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXX XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXX XXXXXX XX XXXXX XXXX XXXXX XX XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXX XX XXXXX XXXXXXXX XXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXX

    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX
XXXXXX
BBBBBBBB