BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXX

  BB BBBBBBBBBBBBBBBBBBBB
    XXXXXXXXXXXXXX XXX XXX XXXXXXXXXXXXXXXXXXX
  BBBBB
  BB BBBBBBBBBBBBBBBBBBBBB
    XXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXX
  BBBBB

  XXXXX XXXXXXXXXXXXX XXXXXXXXXXX
    BBBBBBBBBB
    XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX

    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX
XXXXXX
BBBBBBBB
