BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBB
BBBBB BBBBBBB
XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
XXXXX
    BB BBBBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    BBBBB
    XXXXXXX
    XXXXXXX
    XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXXXXX
XXXXXX
XXXXXXXXX

XXXXXXXX
    XXX X XX
XXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX


BBBBBBBB