BBBBBBB BBBBBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBB
BBBBB BBBBBBB
BBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
     gettext(u'привет') 
    XXXXXXX XXXXXXXXXXXXX XXXXXXX gettext(u'The Page of A Developer') XXXXXXXXX
XXXXXXX
XXXXXXX
BBBBBBBB