BBBB BBBBBBBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXX

    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX

    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
XXXXXXX

XXXXXX
    XXXX XXXXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXXX
    XX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    
    XXXX XXXXXXXXXXXXXXXX XXXX XXXX  XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXX XXXXXXX  

      XXXXX XXXXXXXXXXXXXXXBBBBBBBBBB
      XXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXBBBBBBBBBB
      XXXXXXXXXXXX


          XXXXXXXXXX XXX XXXXXXXXXXXXXXXXXX 
          XXXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX


          XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX



          XX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
          XXXXX
          XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
      XXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXX XXX
    XXXXXX

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX X XXXXX XXXXXXXXX
XXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXX XXXXXXXXXXXXXXBBBBBBBBBB
    
    XXXXX XXXX XX XXXXXXXXX
    XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
    XXXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXX

 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
     XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
     XXXXXXXXXXXX
XX         XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
XX             XXXXXX XXXXXXXXXXXX
XX             XXXXXXXXXX XXXXXXXX
XX             XXXXXXXX XXXXXX XXXXXX
XX         XXXXXX
XX     XXXXXXXXXXXX

XXXXXXX
XXXXXXX