# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fighter', '0004_auto_20170411_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('russian', models.CharField(max_length=250)),
                ('english', models.CharField(max_length=250)),
                ('buttuns', models.CharField(max_length=250)),
            ],
        ),
    ]
