# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighter', '0005_stack'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('russia', models.CharField(max_length=250)),
                ('english', models.CharField(max_length=250)),
                ('buttuns', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Stack',
        ),
    ]
