# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fighter', '0006_auto_20170423_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonone',
            old_name='buttuns',
            new_name='buttons',
        ),
    ]
