# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighter', '0007_auto_20170502_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('russia', models.CharField(max_length=250)),
                ('english', models.CharField(max_length=250)),
                ('buttons', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
