# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-10 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighter', '0010_auto_20170710_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontwo',
            name='buttons',
            field=models.TextField(),
        ),
    ]
