# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighter', '0011_auto_20170710_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonFive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('russia', models.CharField(max_length=250)),
                ('english', models.CharField(max_length=250)),
                ('buttons', models.TextField()),
            ],
            options={
                'verbose_name': 'LessonFive',
            },
        ),
        migrations.CreateModel(
            name='LessonFour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('russia', models.CharField(max_length=250)),
                ('english', models.CharField(max_length=250)),
                ('buttons', models.TextField()),
            ],
            options={
                'verbose_name': 'LessonFour',
            },
        ),
        migrations.CreateModel(
            name='LessonSeven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('russia', models.CharField(max_length=250)),
                ('english', models.CharField(max_length=250)),
                ('buttons', models.TextField()),
            ],
            options={
                'verbose_name': 'LessonSeven',
            },
        ),
        migrations.CreateModel(
            name='LessonSix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('russia', models.CharField(max_length=250)),
                ('english', models.CharField(max_length=250)),
                ('buttons', models.TextField()),
            ],
            options={
                'verbose_name': 'LessonSix',
            },
        ),
        migrations.CreateModel(
            name='LessonThree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('russia', models.CharField(max_length=250)),
                ('english', models.CharField(max_length=250)),
                ('buttons', models.TextField()),
            ],
            options={
                'verbose_name': 'LessonThree',
            },
        ),
    ]
