# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170411_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars/', verbose_name='Изображения'),
        ),
    ]
